@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class, androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package uk.co.scrying.ui.circle

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import uk.co.scrying.*
import uk.co.scrying.ui.components.*

@Composable fun CircleScreen(modifier: Modifier, padding: PaddingValues, state: ScryingUiState, vm: ScryingViewModel) { var peopleTab by remember { mutableStateOf(true) }; var add by remember { mutableStateOf(false) }; Column(modifier.fillMaxSize().padding(padding).padding(16.dp)) { Text("Circle", style = MaterialTheme.typography.titleLarge); SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth().padding(vertical = 12.dp)) { SegmentedButton(peopleTab, { peopleTab = true }, SegmentedButtonDefaults.itemShape(0, 2)) { Text("People") }; SegmentedButton(!peopleTab, { peopleTab = false }, SegmentedButtonDefaults.itemShape(1, 2)) { Text("Devices") } }; if (peopleTab) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("Local people", style = MaterialTheme.typography.titleMedium); FilledTonalButton({ add = true }) { Text("Add person") } }; if (state.people.isEmpty()) EmptyState("No people yet", "Add household members or collaborators. This remains local.") else LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { items(state.people, key = { it.id }) { person -> PersonRow(person, state.agreements.filter { it.personId == person.id }, vm) } }; PrivacyNote("People are local records. Sharing is revocable and requires later pairing.") } else Devices(state, vm) }; if (add) AddPerson({ add = false }, vm::savePerson) }
@Composable private fun PersonRow(person: Person, agreements: List<SharingAgreement>, vm: ScryingViewModel) { var sheet by remember { mutableStateOf(false) }; ScryingCard { ListItem(headlineContent = { Text(person.displayName) }, supportingContent = { Text(person.note.ifBlank { "No note" }) }, leadingContent = { Surface(Modifier.size(40.dp), shape = MaterialTheme.shapes.medium, color = MaterialTheme.colorScheme.secondaryContainer) { Box(contentAlignment = androidx.compose.ui.Alignment.Center) { Text(person.displayName.take(2).uppercase()) } } }, trailingContent = { Text("${agreements.count { it.enabled }} shared") }); TextButton({ sheet = true }) { Text("Sharing") } }; if (sheet) ModalBottomSheet({ sheet = false }) { Column(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Text("Sharing with ${person.displayName}", style = MaterialTheme.typography.titleLarge); listOf(ContributionType.DEVICE_HEALTH to "Device health", ContributionType.BLE_OBSERVER to "BLE observations", ContributionType.WIFI_OBSERVER to "Wi-Fi observations").forEach { (type, label) -> val enabled = agreements.firstOrNull { it.contribution == type }?.enabled ?: false; Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(label); Switch(enabled, { vm.saveAgreement(SharingAgreement(person.id, type, it)) }) } }; TextButton(onClick = { vm.deletePerson(person); sheet = false }, colors = ButtonDefaults.textButtonColors(contentColor = MaterialTheme.colorScheme.error)) { Text("Delete local person") }; PrivacyNote("These settings do not send data until authenticated device pairing exists.") } } }
@Composable private fun Devices(state: ScryingUiState, vm: ScryingViewModel) { LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { item { ScryingCard { Text("This phone", style = MaterialTheme.typography.titleLarge); Text(state.profile.summary); TextButton(vm::refreshProfile) { Text("Refresh capabilities") }; FlowRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) { state.profile.capabilities.take(8).forEach { cap -> AssistChip(onClick = { if (cap.state == CapabilityState.PERMISSION_REQUIRED) vm.refreshProfile() }, label = { Text(cap.title) }, leadingIcon = { Surface(Modifier.size(8.dp), shape = MaterialTheme.shapes.extraSmall, color = capabilityColor(cap.state)) {} }) } }; PrivacyNote("What this phone contributes is controlled from Pulse.") } }; item { Text("Authorised devices", style = MaterialTheme.typography.titleMedium) }; items(state.nodes.filter { it.ownership in setOf(OwnershipState.MINE, OwnershipState.PERMISSION_GRANTED) }, key = { it.id }) { node -> ScryingCard { Text(node.friendlyName, fontWeight = FontWeight.SemiBold); OwnershipBadge(node.ownership); Text(node.capabilities.joinToString().ifBlank { node.category.name.lowercase() }, style = MaterialTheme.typography.labelSmall) } } } }
@Composable private fun AddPerson(dismiss: () -> Unit, save: (Person) -> Unit) { var name by remember { mutableStateOf("") }; var note by remember { mutableStateOf("") }; AlertDialog(onDismissRequest = dismiss, title = { Text("Add person") }, text = { Column { OutlinedTextField(name, { name = it }, label = { Text("Name") }); OutlinedTextField(note, { note = it }, label = { Text("Note") }) } }, confirmButton = { Button(enabled = name.isNotBlank(), onClick = { save(Person(displayName = name.trim(), note = note.trim())); dismiss() }) { Text("Save") } }, dismissButton = { TextButton(dismiss) { Text("Cancel") } }) }
@Composable private fun capabilityColor(state: CapabilityState) = when (state) { CapabilityState.AVAILABLE -> MaterialTheme.colorScheme.secondary; CapabilityState.DISABLED -> MaterialTheme.colorScheme.outline; CapabilityState.PERMISSION_REQUIRED -> MaterialTheme.colorScheme.primary; CapabilityState.UNSUPPORTED -> MaterialTheme.colorScheme.error; CapabilityState.UNKNOWN -> MaterialTheme.colorScheme.tertiary }
